### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by jonahseguin** [tsanga/orbt#12]
# ROADMAP for orbt
_please note: this roadmap is primarily focused on version ALPHA (minimum viable product) and isn't necessarily representational of the end goals for the orbt project and architecture._

### api
- [x] graphql server implementation
- [x] room model
- [x] user model
- [ ] basic room queries and mutations
- [ ] basic user queries and mutations
- [ ] authentication and authorization
- [ ] room auth
- [ ] user auth
- [ ] user store for in-memory storage
- [ ] room store for in-memory storage
- [ ] in-memory broker-based gql subscriptions for rooms
- [ ] subscriptions for room chat, room remote, room members
- [ ] mutations and queries for user colors in rooms
- [ ] improved validation for room queries and mutations
- [ ] correlate subscriptions to a room+user
- [ ] handle connection dropping/closing in gql subscription(s) to handle when a user leaves/disconnects (`fn drop()`)
- [ ] connect vm to room model
- [ ] provide interface for vm to interact with api
- [ ] provide interface to connect remote holder w/ direct vm ws connection
- [ ] room user cursor subscription and/or websocket/mutation for real-time user cursors (non-remote)

### web
- [ ] resolve #10 
- [ ] room page
- [ ] room chat box
- [ ] join room page
- [ ] graphql client
- [ ] user authentication
- [ ] user queries and mutations
- [ ] room queries and mutations
- [ ] room chat subscription 
- [ ] room send chat mutation
- [ ] user set name
- [ ] user set color

### cli
- [ ] wizard setup for orbt application
- [ ] start web app
- [ ] start api app
- [ ] initialize room via api
- [ ] provide url w/ token for the owner of the room to join
- [ ] start vm app
- [ ] commands for managing room + lifecycle

### vm
- [ ] project setup
- [ ] ... todo!()
